force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <description>This is an custom created object Customer</description>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <description>Counting the no of days</description>
    <label>Day Count</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DummyApex.cls
public class DummyApex {
    public static void switchExp(){
        List<sObject> lstCstmr = [Select Day_Count__c from Customer__c LIMIT 1];
    Integer a = Integer.valueOf(lstCstmr.get(0));
    switch on a{
        when 0{
            System.debug('Sunday');
        }
        when 1{
            System.debug('Monday');
        }
        when 2{
             System.debug('Tuesday');
        }
        when 3{
             System.debug('Wednesday');
        }
        when 4{
             System.debug('Thursday');
        }
        when 5{
             System.debug('Friday');
        }
        when 6{
             System.debug('Saturday');
        }
        when else{
            System.debug('Incorrect Selection');
        }
    }
    }
}